### ISSUE TITLE
ubuntu 64 failed install

### ISSUE THREAD

**Issue by zkl99999** [getlantern/lantern-binaries#58]
sudo gdebi lantern-installer-64-bit.deb

Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 61, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 71, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'

**Comment by irol765** [comment]
haha

**Comment by disign-ming** [comment]
tar: 归档被压缩。使用 -J 选项
tar: Error is not recoverable: exiting now
dpkg-deb: 错误: tar subprocess returned error exit status 2
dpkg: 处理归档 lantern-installer-64-bit.deb (--install)时出错：
 dpkg-deb --control subprocess returned error exit status 2
在处理时有错误发生：
 lantern-installer-64-bit.deb

**Comment by disign-ming** [comment]
Deb file error, please replace it as soon as possible

**Comment by qianyue0317** [comment]
> Deb file error, please replace it as soon as possible



> tar: 归档被压缩。使用 -J 选项
> tar: Error is not recoverable: exiting now
> dpkg-deb: 错误: tar subprocess returned error exit status 2
> dpkg: 处理归档 lantern-installer-64-bit.deb (--install)时出错：
> dpkg-deb --control subprocess returned error exit status 2
> 在处理时有错误发生：
> lantern-installer-64-bit.deb

老哥 ， 这个怎么解决啊

**Comment by panghupy** [comment]
我也是这个错误

**Comment by Jiongyu** [comment]
```
tan@tan-pc:~/Downloads$ sudo gdebi lantern-installer-64-bit.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 61, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 71, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'
```

**Comment by Jiongyu** [comment]
```
tan@tan-pc:~/Downloads$ sudo dpkg -i lantern-installer-64-bit.deb 
tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
dpkg-deb: error: subprocess tar returned error exit status 2
dpkg: error processing archive lantern-installer-64-bit.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 lantern-installer-64-bit.deb
```

**Comment by widon1104** [comment]
widon@widon-X555YI:~/Desktop$ sudo dpkg -i lantern-installer-64-bit.deb 
tar: 归档被压缩。使用 -J 选项
tar: Error is not recoverable: exiting now
dpkg-deb: 错误: tar subprocess returned error exit status 2
dpkg: 处理归档 lantern-installer-64-bit.deb (--install)时出错：
 dpkg-deb --control subprocess returned error exit status 2
在处理时有错误发生：
 lantern-installer-64-bit.deb
widon@widon-X555YI:~/Desktop$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
