### ISSUE TITLE
the lantern Installation errors in ubuntu16.04

### ISSUE THREAD

**Issue by Jiongyu** [getlantern/lantern-binaries#70]
I try to install lantern in the ubuntu by three ways as follows:

*1. gdebi*
```
tan@tan-pc:~/Downloads$ sudo gdebi lantern-installer-64-bit.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 61, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 71, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'

```
*2. dpkg*
```
tan@tan-pc:~/Downloads$ sudo dpkg -i lantern-installer-64-bit.deb 
tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
dpkg-deb: error: subprocess tar returned error exit status 2
dpkg: error processing archive lantern-installer-64-bit.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 lantern-installer-64-bit.deb
```
*3. softe-center*
```
got a error window:
Sorry ,this did not work
no flie_to_app results to show
```

**Comment by Jiongyu** [comment]
*1. gdebi*
```
tan@tan-pc:~/Downloads$ sudo gdebi lantern-installer-64-bit.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 61, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 71, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'

```
*2. dpkg*
```
tan@tan-pc:~/Downloads$ sudo dpkg -i lantern-installer-64-bit.deb 
tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
dpkg-deb: error: subprocess tar returned error exit status 2
dpkg: error processing archive lantern-installer-64-bit.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 lantern-installer-64-bit.deb
```
*3. softe-center*
got a error window:
Sorry ,this did not work
no flie_to_app results to show

**Comment by Jiongyu** [comment]
wget https://github.com/getlantern/lantern-binaries/raw/5a840f6960c1bcf62e18ea9982d9a33f18da393e/lantern-installer-64-bit.deb

fixed it.
